# =====================================================
# Felfel Balena Demo MQTT Broker
# =====================================================


# MQTT listener
listener 1883


# Allow username/password authentication
allow_anonymous false


# Authentication file
password_file /mosquitto/config/passwordfile



# Persistence
persistence true

persistence_location /mosquitto/data/



# Logging

log_type all



# MQTT protocol version

protocol mqtt
