###############################################################################
# Telegraf Agent Configuration
###############################################################################

[agent]

  interval = "5s"
  round_interval = true

  metric_batch_size = 1000
  metric_buffer_limit = 10000

  collection_jitter = "0s"

  flush_interval = "5s"
  flush_jitter = "0s"


###############################################################################
# MQTT INPUT
###############################################################################

[[inputs.mqtt_consumer]]

  ## Mosquitto broker inside Balena network
  servers = [
    "tcp://mosquitto:1883"
  ]


  ## Your MQTT topics
  topics = [
    "devices/+/+/telemetry"
  ]


  ## MQTT authentication
  username = "${MQTT_USERNAME}"
  password = "${MQTT_PASSWORD}"


  ## MQTT QoS
  qos = 1


  ## Client ID
  client_id = "telegraf-balena"


  ## Incoming data format
  data_format = "json"

  json_string_fields = [
    "deviceId",
    "deviceType",
    "firmware",
    "status",
    "compressor"
  ]

###############################################################################
# INFLUXDB OUTPUT
###############################################################################

[[outputs.influxdb_v2]]

  urls = [
    "http://influxdb:8086"
  ]


  token = "${INFLUX_TOKEN}"


  organization = "balena-demo"


  bucket = "iot"
